export const ITEMS_FETCH = "ITEMS/FETCH"
export const ITEMS_FETCH_SUCCESS = "ITEMS/FETCH_SUCCESS"
export const ITEMS_FETCH_FAILED = "ITEMS/FETCH_FAILED"

export const RSBUDDY_FETCH = "RSBUDDY/FETCH"
export const RSBUDDY_FETCH_SUCCESS = "RSBUDDY/FETCH_SUCCESS"
export const RSBUDDY_FETCH_FAILED = "RSBUDDY/FETCH_FAILED"
