export const ITEMS_FETCH = "ITEMS/FETCH"
export const ITEMS_FETCH_SUCCESS = "ITEMS/FETCH_SUCCESS"
export const ITEMS_FETCH_FAILED = "ITEMS/FETCH_FAILED"

export const RSBUDDY_FETCH = "RSBUDDY/FETCH"
export const RSBUDDY_FETCH_SUCCESS = "RSBUDDY/FETCH_SUCCESS"
export const RSBUDDY_FETCH_FAILED = "RSBUDDY/FETCH_FAILED"

export const MENTIONS_FETCH = "MENTIONS/FETCH"
export const MENTIONS_FETCH_SUCCESS = "MENTIONS/FETCH_SUCCESS"
export const MENTIONS_FETCH_FAILED = "MENTIONS/FETCH_FAILED"

export const UPDATES_FETCH = "UPDATES/FETCH"
export const UPDATES_FETCH_SUCCESS = "UPDATES/FETCH_SUCCESS"
export const UPDATES_FETCH_FAILED = "UPDATES/FETCH_FAILED"